name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{vars.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{vars.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{vars.DATABASE_NAME}}_test
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retires 5
          
    runs-on: ubuntu-latest
    steps:
      - name : pulling get repo
        uses : actions/checkout@v2
      - name : setting up Python version 3.10
        uses : actions/setup-python@v2
        with :
          python-version: '3.10'
      - name : Update pip
        run : python -m pip install --upgrade pip
      - name : Install all dependencies
        run : pip install -r requirements.txt
      - name : test with pytest
        run : |
          pip install pytest
          pytest