name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name : pulling get repo
        uses : actions/checkout@v2
      - name : setting up Python version 3.10
        uses : actions/setup-python@v2
        with :
          python-version:  3.10
      - name : Update pip
        run : python -m pip install --upgrade pip
      - name : pip install -r requirements.txt